lib/fire_engine_web/router.ex
defmodule FireEngineWeb.Router do
  use FireEngineWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug FireEngine.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FireEngineWeb do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index

    get "/u/quizzes", UserQuizController, :index

    get "/login", AuthController, :login
    get "/auth/cas/callback", AuthController, :callback
    get "/logout", AuthController, :signout


    put "/u/attempts/save/:id", UserAttemptController, :save

    resources "/u/attempts", UserAttemptController
    resources "/admin/quizzes", QuizController
    resources "/admin/questions", QuestionController
    resources "/admin/categories", CategoryController
    resources "/admin/tags", TagController
    resources "/admin/quizzes/:quiz_id/questions", Quiz.QuestionsController
    post "/admin/quizzes/:quiz_id/questions/import", Quiz.QuestionsController, :import, as: "questions_import"
    get "/admin/attempts", UserAttemptController, :index
    delete "/admin/attempts/:id", UserAttemptController, :delete
  end

  # Other scopes may use custom stacks.
    scope "/api/v1", FireEngineWeb do
      pipe_through :api

      resources "user_attempts", Api.V1.UserAttemptController
      resources "quizzes", Api.V1.UserQuizController
      resources "users", Api.V1.UserController
      post "/user_attempts/save/:id", Api.V1.UserAttemptController, :save
      get "/user_attempts/review/:id", Api.V1.UserAttemptController, :review
      get "/not_authorized", PageController, :notauthorized
      get "/authenticate", AuthController, :authenticate

    end
end

lib/fire_engine_web/views/layout_view.ex
defmodule FireEngineWeb.LayoutView do
  use FireEngineWeb, :view

  def logged_in?(conn) do
    conn.assigns[:user]
  end

  def admin_user?(conn) do
    # Placeholder
    conn.assigns[:user].username
    |> FireEngine.Accounts.User.admin?
  end

end

lib/fire_engine_web/templates/layout/app.html.eex
<!DOCTYPE html>

<html lang="en">
<head>

  <!-- Bootstrap CDN -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="<%= static_path(@conn, "/css/app.css") %>" rel="stylesheet">

  <!-- jQuery, Bootstrap JS, Font Awesome, CK Editor -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
  <script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>
</head>

<body>

  <!-- Navbar Container  -->
  <header class="navbar navbar-expand-lg navbar-light bg-light mb-3">

    <!-- Logo -->
    <a class="navbar-brand" href="#"><img src="<%= static_path(@conn, "/images/FireEngine.png") %>" width="150"></a>

    <!-- Hamburger Menu -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-menu-group" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Nav Buttons -->
    <div class="collapse navbar-collapse" id="nav-menu-group">
      <ul class="navbar-nav mr-auto">

          <!-- Only show menu items if logged in -->
          <%= if logged_in?(@conn) do %>

            <!-- Only show Admin if admin -->
            <%= if admin_user?(@conn) do %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="admin-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</a>
                <div class="dropdown-menu" aria-labelledby="admin-dropdown">
                  <%=link "Quiz Bank", to: quiz_path(@conn, :index), class: "dropdown-item" %>
                  <%=link "Question Bank", to: question_path(@conn, :index),class: "dropdown-item" %>
                  <%=link "Question Categories", to: category_path(@conn, :index), class: "dropdown-item" %>
                  <%=link "Question Tag", to: tag_path(@conn, :index),
                  class: "dropdown-item" %>
                </div>
              </li>
            <% end %>
          <% end %>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">

          <!-- Login/Logout -->
          <%= if logged_in?(@conn) do %>
            <%= link "Logout", to: auth_path(@conn, :signout), class: "nav-link" %>
          <%else %>
            <%= link "Login", to: auth_path(@conn,:login), class: "nav-link"  %>
          <% end %>
        </li>
      </ul>
    </div>
  </header>

  <!-- Alerts Container -->
  <div class="alert-container container-fluid">
    <%= unless is_nil(get_flash(@conn, :info)) do %>
      <div class="alert alert-info alert-dismissible fade show" role="alert">
        <%= get_flash(@conn, :info) %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%=unless is_nil(get_flash(@conn, :error)) do %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= get_flash(@conn, :error) %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>

  <!-- Main Content Container -->
  <main role="main">
    <div class="container-fluid">
      <%= render @view_module, @view_template, assigns %>
    </div>
  </main>

  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>