lib/fire_engine_web/router.ex
defmodule FireEngineWeb.Router do
  use FireEngineWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug FireEngine.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FireEngineWeb do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index

    get "/u/quizzes", UserQuizController, :index

    get "/login", AuthController, :login
    get "/auth/cas/callback", AuthController, :callback
    get "/logout", AuthController, :signout


    put "/u/attempts/save/:id", UserAttemptController, :save

    resources "/u/attempts", UserAttemptController
    resources "/admin/quizzes", QuizController
    resources "/admin/questions", QuestionController
    resources "/admin/categories", CategoryController
    resources "/admin/tags", TagController
    resources "/admin/quizzes/:quiz_id/questions", Quiz.QuestionsController
    post "/admin/quizzes/:quiz_id/questions/import", Quiz.QuestionsController, :import, as: "questions_import"
    get "/admin/attempts", UserAttemptController, :index
    delete "/admin/attempts/:id", UserAttemptController, :delete
  end

  # Other scopes may use custom stacks.
    scope "/api/v1", FireEngineWeb do
      pipe_through :api

      resources "user_attempts", Api.V1.UserAttemptController
      resources "quizzes", Api.V1.UserQuizController
      resources "users", Api.V1.UserController
      post "/user_attempts/save/:id", Api.V1.UserAttemptController, :save
      get "/user_attempts/review/:id", Api.V1.UserAttemptController, :review
      get "/not_authorized", PageController, :notauthorized
      get "/authenticate", AuthController, :authenticate

    end
end

lib/fire_engine_web/views/user_attempt_view.ex
defmodule FireEngineWeb.UserAttemptView do
  use FireEngineWeb, :view

  def render("foo.json", %{}) do
    %{message: "foo"}
  end
end

lib/fire_engine_web/templates/user_attempt/edit.html.eex
<h2 class="SectionHeader">Quiz Attempt</h2>


<%= form_for @changeset, user_attempt_path(@conn,:update,@attempt, page: @conn.query_params["page"], quiz_id: @quiz.id), fn f ->  %>
  <%= hidden_input f, :id %>
  <%= hidden_input f, :closed %>
  <%= hidden_input f, :closes %>
  <%= hidden_input f, :grade %>
  <%= hidden_input f, :open %>
  <%= hidden_input f, :quiz_id %>
  <%= hidden_input f, :user_Id %>


  <ol class="list-group">
    <%= inputs_for f, :responses, fn r -> %>
      <%= if Enum.map(@questions,&(&1.id)) |> Enum.member?(r.data.question_id) do %>
      <li class="list-group-item">
        <% q = @questions |> Enum.find(&(&1.id == r.data.question_id)) %>
        <%= hidden_input r, :question_id %>
        <%= raw q.content %>
        <ul class="list-group">
        <%= for a <- q.answers do %>
          <li class="list-group-item">
            <%= radio_button r, :answer_id, a.id %>
            <%= a.answer %>
          </li>
        <% end %>
        </ul>
      </li>
      <% end %>
    <% end %>
  </ol>

<br />
<%= submit "Submit Answers", class: "btn btn-primary btn-block" %>
<% end %>

lib/fire_engine_web/templates/user_attempt/index.html.eex
<h1 class="section-header text-center">
  <%= link to: quiz_path(@conn, :index), class: "btn btn-primary float-left" do %>
    <i class="fas fa-arrow-left"></i> Back to Quiz List
  <% end %>

  <span class="float-right mb-3"><%= @quiz.name %> Attempts</span>
</h1>

<div class="clearfix"></div>

<div class="mb-3">

</div>
<table class="table mb-0 sticky-top">
  <thead class="thead-light">
    <tr>
      <th scope="col">User ID</th>
      <th class="text-center" scope="col" class="text-left">Username</th>
      <th class="text-center" scope="col">Attempt ID</th>
      <th class="text-center" scope="col">Quiz Score</th>
      <th class="text-center" scope="col">Score %</th>
      <th class="text-right" scope="col">Action</th>
    </tr>
    <tr>
      <th colspan="6">
        <%= form_for @conn, user_attempt_path(@conn, :index), [method: :get], fn f -> %>
          <%= hidden_input f, :quiz_id, [value: @quiz.id] %>
          <%= hidden_input f, :page, [page: 1] %>
          <%= search_input f, :user, class: "form-control", placeholder: "Search Usernames" %>
        <% end %>
      </th>
    </tr>
  </thead>
</table>

<table class="table">
  <tbody>
    <%= for qa <- @quiz_attempts.entries do %>
      <tr>
        <td><%= qa.user_id %></td>
        <td class="text-center"><%= qa.username %></td>
        <td class="text-center"><%= qa.attempt %></td>
        <td class="text-center">
          <%= if qa.points_available do %>
            <b><%= qa.point_total %></b> / <b><%= qa.points_available %></b>
          <% else %>
            Scoreless
          <% end %>
        </td class="text-center">
        <td class="text-center">
          <%= if qa.point_percent do %>
            <%= qa.point_percent |> Float.round(2) |> trunc %> %
          <% end %>
        </td>
        <td class="text-right">
          <%= link to: user_attempt_path(@conn, :delete, qa.attempt), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-outline-danger" do %>
            <i class="fas fa-trash"></i> Remove
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

  <th colspan="6">
    Page: <%= @quiz_attempts.page_number..@quiz_attempts.total_pages |> Enum.map(fn(x) -> link(x,to: user_attempt_path(@conn, :index, quiz_id: @quiz.id, page: x)) end) %>
  </td>

</table>

lib/fire_engine_web/templates/user_attempt/show.html.eex
<h2 class="SectionHeader">My Responses</h2>

<hr>
<br>


<table class="table table-bordered">
  <%= for response <- @responses do %>
    <tr>
      <td>
        <b>
        <%= response.question%>
        </b>
      </td>
      <td>
        <%= response.answer%>
      </td>
    </tr>
  <% end %>
</table>

<%= link "Save Quiz", to: user_attempt_path(@conn,:save, @attempt),method: "put", class: "btn btn-primary btn-block" %>