lib/fire_engine_web/router.ex
defmodule FireEngineWeb.Router do
  use FireEngineWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug FireEngine.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FireEngineWeb do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index

    get "/u/quizzes", UserQuizController, :index

    get "/login", AuthController, :login
    get "/auth/cas/callback", AuthController, :callback
    get "/logout", AuthController, :signout


    put "/u/attempts/save/:id", UserAttemptController, :save

    resources "/u/attempts", UserAttemptController
    resources "/admin/quizzes", QuizController
    resources "/admin/questions", QuestionController
    resources "/admin/categories", CategoryController
    resources "/admin/tags", TagController
    resources "/admin/quizzes/:quiz_id/questions", Quiz.QuestionsController
    post "/admin/quizzes/:quiz_id/questions/import", Quiz.QuestionsController, :import, as: "questions_import"
    get "/admin/attempts", UserAttemptController, :index
    delete "/admin/attempts/:id", UserAttemptController, :delete
  end

  # Other scopes may use custom stacks.
    scope "/api/v1", FireEngineWeb do
      pipe_through :api

      resources "user_attempts", Api.V1.UserAttemptController
      resources "quizzes", Api.V1.UserQuizController
      resources "users", Api.V1.UserController
      post "/user_attempts/save/:id", Api.V1.UserAttemptController, :save
      get "/user_attempts/review/:id", Api.V1.UserAttemptController, :review
      get "/not_authorized", PageController, :notauthorized
      get "/authenticate", AuthController, :authenticate

    end
end

lib/fire_engine/assessments/quiz.ex
defmodule FireEngine.Assessments.Quiz do
  use Ecto.Schema
  import Ecto.Changeset
  alias FireEngine.Assessments.Quiz


  schema "fe_quizzes" do
    field :attempts_allowed, :integer
    field :description, :string
    field :name, :string
    field :questions_per_page, :integer
    field :randomize_questions, :boolean, default: false
    field :time_closed, :naive_datetime
    field :time_open, :naive_datetime
    field :color_index, :string
    field :show_answers, :boolean, default: true
    field :auto_submit, :boolean, default: true
    field :time_window, :boolean, default: false
    field :time_limit, :boolean, default: false
    field :time_limit_minutes, :integer

    has_many :quiz_questions, FireEngine.Assessments.QuizQuestion
    many_to_many :questions, FireEngine.Assessments.Question, join_through: "fe_quiz_questions", on_delete: :delete_all, on_replace: :delete
    has_many :attempts, FireEngine.Assessments.Attempt, on_delete: :delete_all

    timestamps(usec: false)
  end

  @doc false
  def changeset(%Quiz{} = quiz, attrs) do
    quiz
    |> cast(attrs, [:name, :description, :attempts_allowed, :randomize_questions, :questions_per_page, :time_open, :time_closed, :color_index, :auto_submit, :time_window, :time_limit, :time_limit_minutes, :show_answers])
    |> validate_required([:name, :description, :attempts_allowed, :randomize_questions, :questions_per_page])
    |> cast_assoc(:questions)
  end
end

lib/fire_engine_web/controllers/quiz/questions_controller.ex
defmodule FireEngineWeb.Quiz.QuestionsController do
  use FireEngineWeb, :controller

  alias FireEngine.Assessments

  plug FireEngine.Plugs.RequireCasAuth
  plug FireEngine.Plugs.VerifyAdmin

  action_fallback FireEngineWeb.FallbackController

  def index(conn,%{"quiz_id" => quiz_id} = params) do
    quiz = Assessments.get_quiz_with_questions(quiz_id)

    current_questions = quiz.questions |> Enum.map(&(&1.content))
    if Map.has_key?(params,"tag") && params["tag"] != "" do
      questions = Assessments.list_fe_questions(current_questions, "%#{params["tag"]}%")
      render(conn,:index,quiz: quiz, questions: questions)
    else
      questions = Assessments.list_fe_questions(current_questions)
      render(conn,:index,quiz: quiz, questions: questions)
    end
  end

  def import(conn,%{"import" => imported, "quiz_id" => quiz_id} = params) do
    questions = Map.values(imported) |> Enum.reject(&(&1 == "false"))

    for question <- questions do
      case Assessments.create_quiz_question(%{quiz_id: quiz_id, question_id: question}) do
        {:ok, _params} ->
          conn
          |> put_flash(:info, "Successfully Imported Questions")
          |> redirect(to: quiz_path(conn,:edit, quiz_id))
      end
    end

  end



end

lib/fire_engine_web/controllers/quiz_controller.ex
defmodule FireEngineWeb.QuizController do
  use FireEngineWeb, :controller

  alias FireEngine.Assessments
  alias FireEngine.Assessments.Quiz
  alias FireEngine.Repo

  plug FireEngine.Plugs.RequireCasAuth
  plug FireEngine.Plugs.VerifyAdmin

  action_fallback FireEngineWeb.FallbackController

  def index(conn, %{"name" => name} = params) do
    page = Assessments.list_fe_quizzes_by_name(name)
                 |> Repo.paginate(params)
    render(conn, "index.html", fe_quizzes: page.entries, page: page)
  end

  def index(conn, params) do
    page = Assessments.list_fe_quizzes
                 |> Repo.paginate(params)
    render(conn, "index.html", fe_quizzes: page.entries, page: page)
  end

  def new(conn, _params) do
    changeset = Assessments.change_quiz(%Quiz{})
    render conn, "new.html", changeset: changeset
  end

  def edit(conn, %{"id" => quiz_id}) do
    quiz = Assessments.get_quiz_with_questions(quiz_id)
    changeset = Assessments.change_quiz(quiz)
    render conn, "edit.html", changeset: changeset, quiz: quiz
  end

  def create(conn, %{"quiz" => quiz_params}) do

    case Assessments.create_quiz(quiz_params) do
      {:ok, %Quiz{} = quiz} ->
        conn
        |> put_flash(:info, "Created #{quiz.name}")
        |> redirect(to: quiz_path(conn,:show,quiz))
      {:error, changeset} ->
        conn
        |> put_flash(:error,  error_parser(changeset))
        |> render("new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    case Assessments.get_quiz_with_questions(id) do
      quiz = %Quiz{} ->
        render(conn, "show.html", quiz: quiz)
      nil ->
        conn
        |> put_status(:not_found)
        |> render(FireEngineWeb.ErrorView, :"404")
    end
  end

  def update(conn, %{"id" => id, "quiz" => quiz_params}) do
    quiz = Assessments.get_quiz_with_questions(id)

    case Assessments.update_quiz(quiz, quiz_params) do
      {:ok, %Quiz{} = quiz} ->
        conn
        |> put_flash(:info, "Updated #{quiz.name}")
        |> redirect(to: quiz_path(conn,:show, quiz))
      {:error, changeset} ->
        conn
        |> put_flash(:error, error_parser(changeset))
        |> render("edit.html", changeset: changeset, quiz: quiz)

    end
  end

  def delete(conn, %{"id" => id}) do
    quiz = Assessments.get_quiz!(id)
    with {:ok, %Quiz{}} <- Assessments.delete_quiz(quiz) do
      conn
      |> put_flash(:info, "Quiz Deleted")
      |> redirect(to: quiz_path(conn, :index))
    end
  end


  #Workaround for JS generated forms. 
  def error_parser(%{changes: %{questions: questions}} = changeset) do
    if questions |> Enum.any?(fn q -> List.keymember?(q.errors,:answers,0) end) do
      "Answer weights cannot exceed total question points"
    else
      "Check your submission"
    end
  end

  def error_parser(changeset), do: "Check your submission"



end

lib/fire_engine_web/views/quiz/questions_view.ex
defmodule FireEngineWeb.Quiz.QuestionsView do
  use FireEngineWeb, :view
  alias FireEngine.Assessments
  alias FireEngine.Repo


end

lib/fire_engine_web/views/quiz_view.ex
defmodule FireEngineWeb.QuizView do
  use FireEngineWeb, :view
  alias FireEngineWeb.QuizView
  alias FireEngineWeb.QuestionView
  use Scrivener.HTML
end

lib/fire_engine_web/templates/quiz/_form.html.eex
<%= form_for @changeset, @path, fn f -> %>
  <div class="quiz-form row">
    <div class="form-group col-sm-12">
      <div class="form-group-item">
        <label>Name <%= error_tag f, :name %></label>
        <%= render "_tooltip.html", direction: "right", text: "The name of the quiz. This is a string." %>
        <%= text_input f, :name, placeholder: "Enter Quiz Name", class: "form-control"%>
      </div>

      <div class="form-group-item">
        <label>Description <%= error_tag f, :description %></label>
        <%= render "_tooltip.html", direction: "right", text: "A description of the quiz." %>
        <%= textarea f, :description, placeholder: "Enter Short Description", class: "form-control"%>
      </div>

      <div class="form-group-item">
        <label>Attempts Allowed <%= error_tag f, :attempts_allowed %></label>
        <%= render "_tooltip.html", direction: "right", text: "The total number of attempts that a user is allowed for the quiz. A value of -1 allows for an infinite number of attempts." %>
        <%= number_input f, :attempts_allowed, placeholder: "i.e. 2", class: "form-control" %>
      </div>
    </div>


    <div class="form-group col-sm-12 col-md-4">
      <div class="form-group-item">
        <%= checkbox f, :time_limit %>
        <%= label f, :time_limit, "Attempt Time Limit"%>
        <%= render "_tooltip.html", direction: "right", text: "Enabling this setting will look at the time limit minutes and will only allow the user to have that amount of time to take the quiz attempt." %>
      </div>

      <div class="form-group-item">
        <%= checkbox f, :auto_submit %>
        <%= label f, :auto_submit, "Auto-Submissions"%>
        <%= render "_tooltip.html", direction: "right", text: "If this setting is enabled, the quiz attempt will automatically submit the quiz attempt once the time limit has been exceeded." %>
      </div>

      <div class="form-group-item">
        <%= checkbox f, :randomize_questions %>
        <%= label f, :randomize_questions, "Randomize Questions"%>
        <%= render "_tooltip.html", direction: "right", text: "Randomize the question order that the student sees in the quiz." %>
      </div>

      <div class="form-group-item">
        <%= checkbox f, :time_window %>
        <%= label f, :time_window, "Quiz Time Window"%>
        <%= render "_tooltip.html", direction: "right", text: "The dates that the quiz is available. You can set a time open and a time close" %>
      </div>

      <div class="form-group-item">
        <%= checkbox f, :show_answers %>
        <%= label f, :time_window, "Show Correct Answers"%>
        <%= render "_tooltip.html", direction: "right", text: "Enabling this setting will show the correct answers after a quiz is submitted." %>
      </div>
    </div>


    <div class="form-group col-sm-12 col-md-8">
      <div class="form-group-item">
        <!-- <%= label f, :questions_per_page, "Questions / Page"%> -->
        <label>Questions / Page <%= error_tag f, :questions_per_page %></label>
        <%= render "_tooltip.html", direction: "right", text: "The number of questions that will be listed per page in the quiz." %>
        <%= number_input f, :questions_per_page, placeholder: "i.e. 5", class: "form-control" %>
      </div>

      <div class="time-limit form-group-item">
        <%= label f, :time_limit_minutes, "Time Limit (mins) / Attempt" %>
        <%= render "_tooltip.html", direction: "right", text: "The number of minutes a user has to make a quiz attempt. This is used only if the Time Limit setting is enabled." %>
        <%= number_input f, :time_limit_minutes, placeholder: "i.e. 10", class: "form-control" %>
      </div>

      <div class="time-window-item form-group-item">
        <%= label f, :time_open, "Quiz Time Open (Year / Month / Day - Hour : Minute)" %>

        <br>
        <%= datetime_select f, :time_open %>
      </div>

      <div class="time-window-item form-group-item">
        <%= label f, :time_closed, "Quiz Time Closed (Year / Month / Day - Hour : Minute)" %><br>
        <%= datetime_select f, :time_closed %>
      </div>
    </div>

    <div class="form-group col-sm-12">
      <h1 class="section-header text-center">
        Questions
        <button type="button" class="btn btn-primary add-question-btn">+ Add Question</button>
      </h1>


      <div class="text-center">
        <%= render "_tooltip.html", direction: "right", text: "Text for Questions and Answers. Points denote the number points a question is worth. This can be any real number. The weight of the question compared to the other questions in a quiz. This can be any real number. For each question, we multiply the weight by the points and then sum the total earned points." %>
      </div>
    </div>


    <!-- Questions List -->
    <!-- Questions List -->

    <div class="question-list-nav col-sm-3">
      <div class="list-group sticky-top" id="question-scrollspy-nav">
        <div class="list-group-item list-group-item-header text-center">
          <h5>Questions</h5>
          <button type="button" class="btn btn-outline-primary btn-block add-question-btn">+ Add Question</button>
        </div>

        <%= inputs_for f, :questions, fn q -> %>
          <a href="#question_<%= q.index %>" class="list-group-item list-group-item-action" questionId="<%= q.index %>">
            Question <%=q.index%>
          </a>
        <% end %>

      </div>
    </div>

    <div class="col-sm-9">
      <div class="question-list" data-spy="scroll" data-target="#question-scrollspy-nav" data-offset="0">

        <%= inputs_for f, :questions, fn q -> %>
          <div class="question-card card border-primary" id="question_<%=q.index%>">
            <div class="card-header">
              <b class="float-left">Question <%=q.index%></b>
              <div class="text-right">
                <button type="button" class="btn btn-danger remove-question-btn" questionId="<%= q.index %>">
                  <i class="fas fa-times"></i>
                  Remove Question
                </button>
              </div>

              <%= textarea q, :content, id: "editor#{q.id}", class: "form-control", placeholder: "Question" %>

              <script>CKEDITOR.replace( "editor<%= q.id %>" )</script>
            </div>


            <div class="question-options card-body">
              <b>Question Weight / Type</b>
              <div class="row">
                <div class="col-4">
                  <%= number_input q, :points, class: "form-control", placeholder: "Points" %>
                </div>

                <div class="col-4">
                  <%= select q, :type,["Multiple Choice", "True/False"], class: "form-control", placeholder: "Type" %>
                </div>

                <div class="col-4">
                  <button type="button" class="btn btn-outline-primary btn-block add-answer-btn" questionId="<%= q.index %>"><i class="fas fa-plus"></i> Add Answer</button>
                </div>
              </div>
            </div>

            <!-- Answers  -->
            <!-- Answers  -->

            <div class="question-answer-list card-footer">
              <b>Answer Text / Weight</b>

              <%= inputs_for q, :answers, fn a -> %>
                <div id="question_<%=q.index%>_answer_<%=a.index%>" class="row">
                  <div class="col-8">
                    <%= text_input a, :answer, class: "form-control", placeholder: "Answer" %>
                  </div>

                  <div class="col-3">
                    <%= number_input a, :weight, step: "0.25", min: "-1.0", max: "1.0", placeholder: "0", class: "form-control"%>
                  </div>

                  <div class="col-1">
                    <button type="button" class="btn btn-outline-danger btn-block remove-answer-btn" questionId="<%= q.index %>" answerId="<%= a.index %>">
                      <i class="fas fa-times-circle"></i>
                    </button>
                  </div>
                </div>
              <% end %>
            </div>

            <!-- End: Answers  -->
            <!-- End: Answers  -->

          </div>
        <% end %>

      </div>
    </div>

    <div class="form-group col-sm-12">
      <%= submit "Save Quiz", class: "btn btn-primary btn-lg btn-block" %>
    </div>

  </div>
<% end %>

lib/fire_engine_web/templates/quiz/_tooltip.html.eex
<a data-toggle="tooltip" data-placement="<%=@direction%>" title="<%=@text%>">
  <i class="fas fa-question-circle text-primary"></i>
</a>

lib/fire_engine_web/templates/quiz/edit.html.eex
<h1 class="section-header text-center">
  Quiz Edit
  <%= link "Import Questions", to: questions_path(@conn, :index, @changeset.data.id), class: "btn btn-primary" %>
</h1>

<%= render FireEngineWeb.QuizView, "_form.html", changeset: @changeset, path: quiz_path(@conn, :update, @quiz) %>

lib/fire_engine_web/templates/quiz/index.html.eex
<div class="admin-quizzes-page">
  <h1 class="section-header text-center">
    Quiz Bank
    <%= button to: quiz_path(@conn,:new), method: "get" , class: "btn btn-primary" do %>
     <i class="fas fa-plus"></i> New Quiz
   <% end %>
  </h1>

  <%= form_for @conn, quiz_path(@conn, :index), [method: :get], fn f -> %>
    <%= search_input f, :name, class: "form-control", placeholder: "Search Questions By Name" %>
  <% end %>

  <table class="quiz-table table mt-4">
    <thead class="thead-light">
      <tr>
        <th scope="col">ID</th>
        <th scope="col" class="text-left">Quiz Name</th>
        <th scope="col"># of Attempts Allowed</th>
        <th scope="col"># of Questions</th>
        <th scope="col">Attempt Time Limit</th>
        <th scope="col">Auto Submissions</th>
        <th scope="col">Randomized Questions</th>
        <th scope="col">Quiz Time Window</th>
        <th scope="col">Quiz Attempts</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody>
      <%= for quiz <- @fe_quizzes do %>
        <tr>
          <td><%= quiz.id %></td>
          <th scope="row"><%= link quiz.name, to: quiz_path(@conn,:show, quiz) %></th>
          <td><%= quiz.attempts_allowed %></td>
          <td><%= Enum.count(quiz.questions)%></td>
          <td>
            <%= if quiz.time_limit do %>
              <i class="fas fa-circle"></i>
            <% else %>
              <i class="far fa-circle text-muted"></i>
            <% end %>
          </td>

          <td>
            <%= if quiz.auto_submit do %>
              <i class="fas fa-circle"></i>
            <% else %>
              <i class="far fa-circle text-muted"></i>
            <% end %>
          </td>

          <td>
            <%= if quiz.randomize_questions do %>
              <i class="fas fa-circle"></i>
            <% else %>
              <i class="far fa-circle text-muted"></i>
            <% end %>
          </td>

          <td>
            <%= if quiz.time_window do %>
              <i class="fas fa-circle"></i>
            <% else %>
              <i class="far fa-circle text-muted"></i>
            <% end %>
          </td>

          <td>
            <%= link to: user_attempt_path(@conn, :index, quiz_id: quiz.id, page: 1), class: "btn btn-outline-primary btn-block m-0" do %>
              <i class="fas fa-list-ul"></i> View <%= Enum.count(quiz.attempts)%> Attempts
            <% end %>
          </td>

          <td>
            <div class="btn-group">
              <%= link to: quiz_path(@conn, :edit, quiz), class: "btn btn-primary btn-block m-0" do %>
                <i class="fas fa-edit"></i> Edit
              <% end %>

              <%= link to: quiz_path(@conn, :delete, quiz), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-outline-danger m-0" do %>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>
  <%= pagination_links @page %>
</div>

lib/fire_engine_web/templates/quiz/new.html.eex
<h1 class="section-header text-center">New Quiz</h1>

<%=render FireEngineWeb.QuizView, "_form.html", changeset: @changeset, path: quiz_path(@conn, :create)%>

lib/fire_engine_web/templates/quiz/show.html.eex
<h1 class="section-header text-center">
  <%= link to: quiz_path(@conn, :index), class: "btn btn-primary float-left" do %>
    <i class="fas fa-arrow-left"></i> Back to List
  <% end %>
  <%= link to: quiz_path(@conn, :edit, @quiz), class: "btn btn-outline-primary ml-1 float-left" do %>
    <i class="fas fa-edit"></i> Edit Quiz
  <% end %>

  <%= link to: quiz_path(@conn, :delete, @quiz), method: :delete, class: "btn btn-outline-danger ml-1 float-left" do %>
    <i class="fas fa-trash"></i> Delete Quiz
  <% end %>
  <span class="float-right mb-3"><%= @quiz.name %></span>
</h1>

<div class="clearfix"></div>

<table class="table">
  <tbody>
    <tr>
      <th col="row">Description</th>
      <td class="text-right"><%= @quiz.description %></td>
    </tr>

    <tr>
      <th col="row">Attempts Allowed</th>
      <td class="text-right"><%= @quiz.attempts_allowed %></td>
    </tr>

    <tr>
      <th col="row">Attempt Time Limit?</th>
      <td class="text-right"><%= @quiz.time_limit %></td>
    </tr>

    <%= if @quiz.time_limit do %>
    <tr>
      <th col="row">
        <i class="fas fa-angle-right"></i>
        Time per Attempt (minutes)
      </th>
      <td class="text-right"><%= @quiz.time_limit_minutes %></td>
    </tr>
    <% end %>

    <tr>
      <th col="row">Auto Submissions?</th>
      <td class="text-right"><%= @quiz.auto_submit %></td>
    </tr>

    <tr>
      <th col="row">Randomize Questions?</th>
      <td class="text-right"><%= @quiz.randomize_questions %></td>
    </tr>

    <tr>
      <th col="row">Quiz Time Window?</th>
      <td class="text-right"><%= @quiz.time_window %></td>
    </tr>

    <tr>
      <th col="row">Show Answers</th>
      <td class="text-right"><%= @quiz.show_answers %></td>
    </tr>


    <%= if @quiz.time_window do %>
      <tr>
        <th col="row">
          <i class="fas fa-angle-right"></i>
          Quiz Open
        </th>
        <td class="text-right"><%= @quiz.time_open %></td>
      </tr>
      <tr>
        <th col="row">
          <i class="fas fa-angle-right"></i>
          Quiz Closed
        </th>
        <td class="text-right"><%= @quiz.time_closed %></td>
      </tr>
    <% end %>

    <tr>
      <th col="row">Questions Per Page</th>
      <td class="text-right"><%= @quiz.questions_per_page %></td>
    </tr>

  </tbody>
</table>

<h1 class="section-header">
  <span class="float-left mb-3">Questions</span>
  <span class="float-right mb-3">Answers (Weight)</span>
</h1>

<div class="clearfix"></div>

<table class="table">
  <tbody>
    <%= for question <- @quiz.questions do %>
      <tr>
        <td><%= raw(question.content) %></td>
        <!-- <td><%= question.points %></td> -->
        <td class="">
          <ol type="A">
            <%= for answer <- question.answers do %>
              <li><%= raw(answer.answer) %> (<%= answer.weight %>)</li>
            <% end %>
          </ol>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>